#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2019 Joyent, Inc.
#

#
# Check if the Triton repos are prepared (branched
# as appropriate) for a Triton/SmartOS release build. Will also apply
# missing branch with the '-a' flag.
#
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi

set -o errexit
set -o pipefail

#---- globals, config

TOP=$(cd $(dirname $0)/../; pwd)
WORKDIR="$TOP/tmp/check-repos-for-release"


#---- functions

function usage() {
    if [[ -n "$1" ]]; then
        echo "error: $1"
        echo ""
    fi
    echo "Usage:"
    echo "  check-repos-for-release [<options>] [release-]YYYYMMDD"
    echo ""
    echo "Options:"
    echo "  -c CREDS        Provide creds for mo.joyent.com. If not given"
    echo "                  will use 'MOLYBDENUM_CREDENTIALS' envvar."
    echo "  -a              Create branch (*A*pply) if it is missing"
    echo "  -t TARGET       Just run for the given Jenkins target. If not given"
    echo "                  then all 'jr' targets with 'mg' labels are used."
    echo "                  Can be specified multiple times."
    echo ""
    echo "Examples:"
    echo "  check-repos-for-release 20111020"
    echo "  check-repos-for-release -t usbheadnode 20111020"
    echo "  check-repos-for-release -a release-20111020"
    exit 1
}

function get_repo_url_from_targ {
    local targ=$1
    if [[ -z "$targ" ]]; then
        targ='*'
    fi
    local urls=$(jr list -H -l mg=$targ -o httpsCloneUrl)
    local ret=""
    for url in $urls; do
        ret="$ret $(echo $url)"
    done
    echo $ret
}

function get_repo_name_from_url {
    targ=$1
    echo $targ | cut -d ':' -f2 | xargs -I {} basename {} .git
}

function apply_missing_to_repo {
    local repo_url=$1
    local branch=$2

    echo "Branch repo $repo_url for release: branch '$branch'"
    repo_name=$(get_repo_name_from_url $repo_url)
    mkdir -p $WORKDIR
    cd $WORKDIR
    if [[ -d "$repo_name" ]]; then
        (cd $repo_name && git checkout master && git pull --rebase origin master)
    else
        git clone $repo_url $repo_name;
    fi
    cd $repo_name
    git checkout master
    if [[ -n "$branch" ]]; then
      git checkout -B $branch
      git push -q origin $branch
    fi
    git checkout master   # go back to master branch for subsequent runs
}

function check_repo_url {
    local repo_url=$1
    local targ=$2   # optional

    repo_name=$(get_repo_name_from_url $repo_url)
    local hit
    if [[ -d "$WORKDIR/$repo_name" ]]; then
        hit=$(cd $WORKDIR/$repo_name && git branch -a | (grep remotes/origin/$BRANCH || true))
    fi
    if [[ -z "$hit" ]]; then
        hit=$(curl -sS https://mo.joyent.com/api/repos/$repo_name/refs -u $CREDS \
            | json branches \
            | grep "\"$BRANCH\"" \
            || true)
    fi
    if [[ -z "$hit" ]]; then
      if [[ $APPLY -eq 1 ]]; then
        echo "Repo $repo_url ('$targ' target): missing '$BRANCH' branch"
        apply_missing_to_repo $repo_url "$BRANCH"
      else
        echo "Repo $repo_url ('$targ' target): FAIL (no '$BRANCH' branch, use -a to apply)"
      fi
    else
      echo "Repo $repo_url ('$targ' target): OK"
    fi
}

function check_targ {
    local targ=$1
    local repo_urls="$(get_repo_url_from_targ $targ)"
    for repo_url in $repo_urls; do
        check_repo_url $repo_url $targ
    done
}


#---- mainline

APPLY=0   # whether to apply a branch to repo
CREDS=
TARGETS=
while getopts "hac:t:" c; do
    case "$c" in
    h)
        usage
        ;;
    a)
        APPLY=1
        ;;
    c)
        CREDS=$OPTARG
        ;;
    t)
        TARGETS="$TARGETS $OPTARG"
        ;;
    *)
        usage "illegal option -- $OPTARG"
        ;;
    esac
done
shift $((OPTIND - 1))

RELEASE=$1
if [[ -z "$RELEASE" ]]; then
    usage "no RELEASE given"
fi
if [[ -n "$(echo "$RELEASE" | grep '^[0-9]\{8\}$' || true)" ]]; then
    # YYYYMMDD
    BRANCH=release-$RELEASE
elif [[ -n "$(echo "$RELEASE" | grep '^release-[0-9]\{8\}$' || true)" ]]; then
    BRANCH=$RELEASE
else
    fatal "'$RELEASE' does not match '[release-]YYYYMMDD'"
fi

if [[ -z "$CREDS" ]]; then
    CREDS=$MOLYBDENUM_CREDENTIALS
fi
if [[ -z "$CREDS" ]]; then
    usage "no mo.joyent.com crendentials: use '-c CREDS' or set MOLYBDENUM_CREDENTIALS"
fi

for command in jr json; do
    $command -h 2>&1 > /dev/null || fatal "Unable to run $command, please check your \$PATH"
done

if [[ -z "$JR_MANIFESTS" ]]; then
    fatal "$(basename $0): error: \$JR_MANIFESTS should be set in the environment. \
    Example value: \
    JR_MANIFESTS=/Volumes/projects/triton.git/tools/jr-manifest.json,/Volumes/projects/manta.git/tools/jr-manifest.json,/Volumes/projects/smartos-live.git/tools/jr-manifest.json"
fi

if [[ -z "$TARGETS" ]]; then
    # gets a list of the 'mg' label, which is the jenkins job name.
    TARGETS=$(jr list -H -l mg,release -o labels | json -ag mg | sort -u | \
        grep -v sdcsso)
fi

for targ in $TARGETS; do
  if [[ $targ == 'all' ]]; then
    continue
  fi
  check_targ $targ
done
