#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2020 Joyent, Inc.
#

#
# Create a Jenkinsfile corresponding to a weekly build and compare it to
# the weekly-build branch of this repository if it differs from the current
# Jenkinsfile.
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail


#---- globals, config

TOP=$(cd $(dirname $0)/../../; pwd)
CACHEDIR="/var/tmp/weekly-build-cache"
mkdir -p $CACHEDIR

# Assume 'jr' is on the $PATH, but we'll check for that later
JR=jr

JENKINSFILE=/tmp/Jenkinsfile.$$

AGENTS="sdc-agents-core
    triton-cmon-agent
    sdc-cn-agent
    sdc-net-agent
    sdc-vm-agent
    sdc-hagfish-watcher
    sdc-smart-login
    sdc-amon
    sdc-firewaller-agent
    sdc-config-agent"

PLATFORM="smartos-live
    illumos-extra
    illumos-joyent
    illumos-kvm-cmd
    illumos-kvm
    kbmd
    mdata-client
    sdc-ur-agent"

# Set the branch triton.git needs to be on in order to do one of these builds
WHEN_BRANCH="weekly-build"
# Only build if a user has pushed the 'Build now' button (or similar API call)
TRIGGERED_CLAUSE="triggeredBy cause: 'UserIdCause'"


#---- functions

function usage
{
    local exitStatus=0

    if [[ -n "$1" ]]; then
        exitStatus=1
        echo "error: $1" >&2
        echo ""
    fi
    echo "Usage:"
    echo "  weekly-build [<options>] [release-]YYYYMMDD"
    echo ""
    echo "Options:"
    echo "  -h          Print this help and exit."
    echo "  -n          Do a dry-run, don't actually branch."
    echo "  -s          Only build the SmartOS (aka 'platform') repos."
    echo ""

    exit $exitStatus
}

function fatal
{
    echo "$0: fatal error: $*"
    exit 1
}

#---- mainline

optDryRun=false
optYes=false
while getopts "hnsy" opt; do
    case "$opt" in
    h)
        usage
        ;;
    n)
        optDryRun=true
        ;;
    s)
        optJustSmartos=true
        ;;
    *)
        usage "illegal option -- $OPTARG"
        ;;
    esac
done
shift $((OPTIND - 1))

function ensure_jr {
    git clone https://github.com/joyent/joyent-repos $CACHEDIR/joyent-repos
    cd $CACHEDIR/joyent-repos
    make all
    export JR=$CACHEDIR/joyent-repos/bin/jr
}

json -h 2>&1 >/dev/null || \
    fatal "Unable to run $command, please check your \$PATH"
$JR -h 2>&1 > /dev/null || ensure_jr

if [[ -z "$JR_MANIFESTS" ]]; then
    # Despite this script being in triton.git, it's not on the master branch
    # so let's ensure we use that branch for jr-manifest data instead.
    for repo in triton manta smartos-live; do
        git clone https://github.com/joyent/$repo $CACHEDIR/$repo
    done
    cd $TOP
    export JR_MANIFESTS=$CACHEDIR/triton/tools/jr-manifest.json,$CACHEDIR/smartos-live/tools/jr-manifest.json,$CACHEDIR/manta/tools/jr-manifest.json

    # There is a chicken/egg problem here, in that the 'weekly-build' branch
    # might have an old copy of the script that we're running. Check that it's
    # current, and bail out it not.
    if [[ -f $CACHEDIR/triton/tools/releng/weekly-build ]]; then
        set +o errexit
        diff ${TOP}/tools/releng/weekly-build \
            $CACHEDIR/triton/tools/releng/weekly-build
        if [[ $? -ne 0 ]]; then
            echo "Error: the 'weekly-build' branch contains a stale copy of " \
                "./tools/releng/weekly-build. Please cherry-pick it from " \
                "'master' onto the 'weekly-build' branch."
            exit 1
        fi
        set -o errexit
    fi
fi

# Use Joyent repo metadata (https://github.com/joyent/joyent-repos) to list
# (a) public and (b) release repositories.
if [[ "$optJustSmartos" == "true" ]]; then
    repos=$($JR list -l smartos,release,public -Ho name)
else
    repos=$($JR list -l release,public -Ho name)
fi

#
# Generate a Goovy expression that returns true if the 'COMPONENT' build
# parameter is either empty, or includes the name of the component. We use
# the resulting expression in a 'when {..}' clause to determine whether to
# build a given component. This is identical to the logic also held in
# joyTriggerTritonComp, but allows us to include that expression in the
# generated Jenkinsfile, rather than hiding it in a library and allows the
# pipeline view to show why a component build was skipped.
#
function compute_expression {
    COMPONENT=$1
    echo "expression { params.COMPONENTS == \"\" || params.COMPONENTS =~ \".*$COMPONENT.*\" }"
}

function jenkins_header {
    # Write the Jenkinsfile header
    YEAR=$(date +%Y)
    cat > $JENKINSFILE <<EOF
/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * Copyright $YEAR Joyent, Inc.
 */

@Library('jenkins-joylib@v1.0.6') _

pipeline {

    agent {
        label joyCommonLabels(image_ver: '19.4.0')
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '30'))
        timestamps()
        parallelsAlwaysFailFast()
    }
    parameters {
        string(
            name: 'COMPONENT_BRANCH',
            defaultValue: 'master',
            description:
                'The branch of the Triton/Manta components to build.'
            )
        string(
            name: 'COMPONENTS',
            defaultValue: '',
            description:
                'A space separated list of the repositories to build. ' +
                'By default, all components are included, but if any are ' +
                'specified here, <strong>only</strong> those are built, ' +
                'apart from sdc-headnode, which is automatically built ' +
                'unless this is a SmartOS-only build.'
            )
    }

    stages {
EOF
}

function compare_jenkinsfile_stage {
    cat >> $JENKINSFILE <<EOF
        stage('compare jenkinsfile') {
            when { branch '$WHEN_BRANCH' }
            steps {
                /*
                * This checks that the Jenkinsfile in the checked-out workspace
                * matches the one we'd otherwise generate. Run this first to
                * prevent wasting time building incorrect components.
                */
                nodejs('sdcnode-v8-zone64') {
                    sh './tools/releng/weekly-build'
                }
            }
        }
EOF
}

function triton_stage {
    # Builds all Triton/Manta components in parallel. Note the when-clause
    # doesn't include a $EXPRESSION_CLAUSE since this top-level stage simply
    # collects a series of other stages in parallel.
    cat >> $JENKINSFILE <<EOF
        stage('triton/manta components') {
            when {
                allOf {
                    branch '$WHEN_BRANCH'
                    $TRIGGERED_CLAUSE
                }
            }
        /*
         * This builds all components required for the headnode in parallel.
         * We don't indent the enclosed stages to improve readability.
         */
            parallel {
EOF
    platform_stage
    if [[ -z "$optJustSmartos" ]]; then
        component_stage
    fi
    cat >> $JENKINSFILE <<EOF
            }
        /* End triton/manta component parallel */
        }
EOF
    # We can't nest a stage that includes a parallel directive
    # inside another parallel directive. Fortunately, the agent builds
    # don't take long, so we'll live with it.
    if [[ -z "$optJustSmartos" ]]; then
        agent_stage
    fi
}


function platform_stage {
    # Include the platform build stage
    EXPRESSION_CLAUSE=$(compute_expression smartos-live)

    if [[ -n "$optJustSmartos" ]]; then
        PLATFORM_FLAVOR="text(name: 'PLATFORM_BUILD_FLAVOR', value: 'smartos')"
    else
        PLATFORM_FLAVOR="text(name: 'PLATFORM_BUILD_FLAVOR', value: 'triton-and-smartos')"
    fi

    cat >>  $JENKINSFILE <<EOF
        stage('platform build') {
            when {
                allOf {
                    branch '$WHEN_BRANCH'
                    $TRIGGERED_CLAUSE
                    $EXPRESSION_CLAUSE
                }
            }
            steps {
                build(job: 'joyent-org/smartos-live/' + env.COMPONENT_BRANCH,
                    wait: true,
                    parameters: [
                        text(name: 'CONFIGURE_PROJECTS',
                            value:
                            'illumos-extra: ' + env.COMPONENT_BRANCH + ': origin\n' +
                            'illumos: ' + env.COMPONENT_BRANCH + ': origin\n' +
                            'local/kbmd: ' + env.COMPONENT_BRANCH + ': origin\n' +
                            'local/kvm-cmd: ' + env.COMPONENT_BRANCH + ': origin\n' +
                            'local/kvm: ' + env.COMPONENT_BRANCH + ': origin\n' +
                            'local/mdata-client: ' + env.COMPONENT_BRANCH + ': origin\n' +
                            'local/ur-agent: ' + env.COMPONENT_BRANCH + ': origin'),
                        booleanParam(name: 'BUILD_STRAP_CACHE', value: false),
                        $PLATFORM_FLAVOR
                    ])
            }
        }
EOF
}

function agent_stage {
    # builds all agents and the agents installer shar. We don't include a
    # $EXPRESSION_CLAUSE yet, since we're just collecting a series of other
    # stages in parallel.
    cat >> $JENKINSFILE <<EOF
        /*
         * Build all agents in parallel, then build the agents-installer
         * which bundles them into a shar archive.
         */
        stage('agents parallel') {
            when {
                allOf {
                    branch '$WHEN_BRANCH'
                    $TRIGGERED_CLAUSE
                }
            }
            parallel {
EOF
    for agent in $AGENTS; do
        EXPRESSION_CLAUSE=$(compute_expression $agent)
        cat >> $JENKINSFILE <<EOF
                stage('$agent') {
                    steps {
                        joyTriggerTritonComp(
                            repo: "$agent",
                            whenBranch: "$WHEN_BRANCH",
                            compBranch: env.COMPONENT_BRANCH,
                            isAgentBuild: true)
                    }
                }
EOF
    done
    cat >> $JENKINSFILE <<EOF
            }
        }
EOF
    EXPRESSION_CLAUSE=$(compute_expression sdc-agents-installer)
    cat >> $JENKINSFILE <<EOF
        stage('agents-installer') {
            steps {
                joyTriggerTritonComp(
                    repo: "sdc-agents-installer",
                    whenBranch: "$WHEN_BRANCH",
                    compBranch: env.COMPONENT_BRANCH)
            }
        }
EOF
}

function component_stage {
    # Now build everything other than the agents, the headnode and the platform
    SKIP_COMPONENTS="$AGENTS $PLATFORM sdc-agents-installer sdc-headnode "
    for skip_component in $SKIP_COMPONENTS; do
            echo $skip_component
    done | sort > /tmp/weekly-build-skip.$$

    set +o errexit
    for repo in $repos; do
        SHOULD_SKIP=$(cat /tmp/weekly-build-skip.$$ | grep "^$repo\$")
        if [[ -n "$SHOULD_SKIP" ]]; then
            continue
        fi
        EXPRESSION_CLAUSE=$(compute_expression $repo)
        cat >> $JENKINSFILE <<EOF
        stage('$repo') {
            steps {
                joyTriggerTritonComp(
                    repo: "$repo",
                    whenBranch: "$WHEN_BRANCH",
                    compBranch: env.COMPONENT_BRANCH)
            }
        }
EOF
    done
    set -o errexit
    rm /tmp/weekly-build-skip.$$
}

function headnode_stage {
    #
    # Note that we always build sdc-headnode, we don't have an EXPRESSION_CLAUSE
    # for it. We don't build this if doing a SmartOS-only build.
    #
    cat >> $JENKINSFILE <<EOF
        /*
         * Now that all components are built, build the headnode images.
         */
        stage('sdc-headnode') {
            when {
                allOf {
                    branch '$WHEN_BRANCH'
                    $TRIGGERED_CLAUSE
                }
            }
            steps {
                build(
                    job: 'joyent-org/sdc-headnode/' + env.COMPONENT_BRANCH,
                    wait: true,
                    parameters: [
                        text(name: 'CONFIGURE_BRANCHES',
                            value:
                            "bits-branch: " + env.COMPONENT_BRANCH),
                        booleanParam(name: 'INCLUDE_DEBUG_STAGE', value: true)
                    ])
            }
        }
EOF
}

function jenkins_footer {
# Write the Jenkinsfile footer
cat >>  $JENKINSFILE <<EOF
    }
    post {
        always {
            joyMattermostNotification(channel: 'jenkins')
        }
    }
}
EOF
}

jenkins_header
compare_jenkinsfile_stage
triton_stage
if [[ -z "$optJustSmartos" ]]; then
    headnode_stage
fi
jenkins_footer

if [[ -d $CACHEDIR ]]; then
    echo "removing cache dir"
    rm -rf $CACHEDIR
fi

set +o errexit
# Compare what we generated to what is in the workspace.
grep -v 'Copyright .* Joyent, Inc.' $TOP/Jenkinsfile > /tmp/Jenkinsfile.committed.$$
grep -v 'Copyright .* Joyent, Inc.' $JENKINSFILE > /tmp/Jenkinsfile.generated.$$
diff /tmp/Jenkinsfile.committed.$$ /tmp/Jenkinsfile.generated.$$
RES=$?
rm /tmp/Jenkinsfile.committed.$$ /tmp/Jenkinsfile.generated.$$
if [[ $RES -ne 0 ]]; then
    echo "New Jenkinsfile differs from committed version, please update it."
    echo "See $JENKINSFILE"
    exit 1
else
    echo "Weekly build Jenkinsfile is current."
    exit 0
fi
